# Generated by Django 5.2.1 on 2026-01-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens',
            field=models.IntegerField(default=20),
        ),
    ]
