# Generated by Django 5.2.1 on 2025-05-13 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_level', models.CharField(max_length=10)),
                ('yelp_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('food_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.foodrecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('late_night', 'Late Night')], max_length=15)),
                ('mood', models.CharField(choices=[('energized', 'Energized'), ('lazy_day', 'Lazy Day'), ('comfort_craving', 'Comfort Craving'), ('explorative', 'Wants to Explore'), ('health_focused', 'Health Focused')], max_length=30)),
                ('diet_type', models.CharField(choices=[('balanced', 'Balanced Diet'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto')], max_length=30)),
                ('serving_size', models.CharField(choices=[('solo', 'Just Me'), ('couple', 'Couple Meal'), ('family', 'Family Size'), ('party', 'Party / Group')], max_length=15)),
                ('spice_level', models.CharField(choices=[('none', 'No Spice'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], max_length=10)),
                ('health_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Weight Maintenance'), ('detox', 'Detox / Cleanse'), ('energy_boost', 'Energy Boost'), ('general_wellness', 'General Wellness')], max_length=30)),
                ('cost_range_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_range_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodrecommendation',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.userpreference'),
        ),
    ]
